import Head from "next/head";
import { Container } from "@chakra-ui/react";
import HackathonCard from "@/components/card";
import Header from "@/components/header";


export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container
          display="grid"
          placeItems="center"
          maxW="container.md"
          py={8}
        >
          <Header />
          <HackathonCard />
        </Container>
      </main>
    </>
  );
}
